# Generated by Django 4.2.19 on 2025-05-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_detail',
            field=models.ImageField(blank=True, default='posts/default_detail.jpg', null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_home',
            field=models.ImageField(blank=True, default='posts/default_home.jpg', null=True, upload_to='posts/'),
        ),
    ]
