# Generated by Django 4.2.19 on 2025-05-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_remove_post_image_post_image_detail_post_image_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='counted_views',
            field=models.IntegerField(default=0),
        ),
    ]
