# Generated by Django 4.2.19 on 2025-05-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_alter_post_counted_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_detail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_home',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='posts/default.jpg', null=True, upload_to='posts/'),
        ),
    ]
