# Generated by Django 4.2.19 on 2025-05-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product/question_mark.jpg', null=True, upload_to='product/'),
        ),
    ]
