# Generated by Django 4.2.19 on 2025-05-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_product_updated_date_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'able to show'), (1, 'unable to show')], default=1),
        ),
    ]
