# Generated by Django 4.2.19 on 2025-05-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='pro_category',
        ),
    ]
