# Generated by Django 4.2.19 on 2025-05-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0007_rename_category_product_pro_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Pro_Category',
        ),
    ]
